INTAP-85: Issue entity, bundle structure.
Florin1/platform-application pull request #1
Opened 2016-09-29 15:11 UTC by Florin1

2016-10-18 09:16 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Controller/IssueController.php
> +use Academic\Bundle\BugTrackingBundle\Form\Handler\IssueHandler;
Please reorder the dependencies.

``` php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;

use Academic\Bundle\BugTrackingBundle\Entity\Issue;
use Academic\Bundle\BugTrackingBundle\Form\Handler\IssueHandler; 
use Academic\Bundle\BugTrackingBundle\Form\Type\IssueType;
```

2016-10-18 09:16 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Controller/IssueController.php
> +    public function indexAction()
All methods with parameters should have @param docblock.
All methods that return something should have @return docblock.

2016-10-18 09:16 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Controller/IssueController.php
> +        return [
This return can be compressed to one line.

2016-10-18 09:16 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/DependencyInjection/Configuration.php
> +        // Here you should define the parameters that are allowed to
Is this comment required?

2016-10-18 09:16 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Resources/config/importexport.yml
> +             - { name: oro_importexport.template_fixture }
Please add a new line at the end of all files, even the .yml ones.

2016-10-18 11:55 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Form/EventListener/IssueSubscriber.php
> +use Oro\Bundle\UserBundle\Entity\User;
Separate different vendors.

2016-10-18 12:45 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Migrations/Data/ORM/LoadIssueData.php
> +    public function load(ObjectManager $manager)
Add phpdoc.

2016-10-18 12:46 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Migrations/Schema/v1_1/AcademicBugTrackingBundle.php
> +use Oro\Bundle\MigrationBundle\Migration\Migration;
Separate vendors.

2016-10-18 12:46 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Migrations/Schema/v1_1/AcademicBugTrackingBundle.php
> +use Academic\Bundle\BugTrackingBundle\Entity\Issue;
Separate vendors.

2016-10-18 14:06 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Resources/translations/messages.en.yml
> +                    label: 'Edit'
Add new line.

2016-10-18 14:06 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/index.html.twig
> +{% endblock %}
Add new line.

2016-10-18 14:06 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/searchResult.html.twig
> +] %}
Add new line.

2016-10-18 14:07 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/update.html.twig
> +{% endblock content_data %}
Add new line.

2016-10-18 14:07 UTC, dandries commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/view.html.twig
> +{% endblock content_data %}
Add new line.

2016-10-21 08:44 UTC, AlexPuscas commented
Make sure you can only create a Subtask to a Story

2016-10-21 08:49 UTC, AlexPuscas commented
Do you really need DependencyInjection\Configuration?

2016-10-21 08:59 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Tests/Functional/Controller/IssueControllerTest.php
> +    public function testUpdateAction()
You can pass the ID of the issue from one test to another, and so perform all CRUD actions for the same issue, by returning the ID and depending on the previous test.

2016-10-21 09:09 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Tests/Functional/Controller/IssueControllerTest.php
> +        $this->assertContains('General Information', $result->getContent());
You should test something specific for an issue, like name or code.

2016-10-21 09:09 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Tests/Functional/Entity/Repository/IssueRepositoryTest.php
> +        $this->assertArrayHasKey('status', $result);
You should also check the result of the query.

2016-10-21 09:09 UTC, AlexPuscas commented on src/Academic/Bundle/BugTrackingBundle/Tests/Unit/Form/Type/IssueTypeTest.php
> +        $this->issueType->buildForm($this->builder, []);
You should actually test the submit of the form. See http://symfony.com/doc/current/form/unit_testing.html

2016-10-21 09:11 UTC, AlexPuscas commented
Please unit test classes from DependencyInjection folder.

2016-10-31 15:37 UTC, yshyshkin commented
Please, fix code style issues:
```
maniac@laphere:/opt/www/academ-fo$ phpcs --encoding=utf-8 --extensions=php --standard=psr2 src/ -p
..........EE....E..............


FILE: ...fo/src/Academic/Bundle/BugTrackingBundle/Form/Type/IssueType.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 84 | ERROR | [x] Only one argument is allowed per line in a
    |       |     multi-line function call
 87 | ERROR | [x] Closing parenthesis of a multi-line function call
    |       |     must be on a line by itself
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: .../Bundle/BugTrackingBundle/Form/EventListener/IssueSubscriber.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 60 | ERROR | [x] Expected 0 spaces before closing bracket; newline
    |       |     found
 66 | ERROR | [x] Expected 0 spaces before closing bracket; newline
    |       |     found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: ...ackingBundle/Tests/Functional/Controller/IssueControllerTest.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 78 | ERROR | [x] Multi-line function call not indented correctly;
    |       |     expected 8 spaces but found 12
 78 | ERROR | [x] Only one argument is allowed per line in a
    |       |     multi-line function call
 78 | ERROR | [x] Closing parenthesis of a multi-line function call
    |       |     must be on a line by itself
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2016-10-31 16:14 UTC, yshyshkin requested changes

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Form/Type/IssueType.php
> +                EntityType::class, array(
Please, maintain consistency and use short syntax array all over the code.

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Form/EventListener/IssueSubscriber.php
> +            return $entityRepository->createQueryBuilder('user')
Please, move direct query builder manipulation to entity repository and then call appropriate method here- form layer should not be aware about database structure.

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Placeholder/PlaceholderFilter.php
> +    public function __construct(Request $request)
Please, add missing phpdoc.

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/index.html.twig
> +    exportTitle: 'Export',
Please, translate this label.

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Resources/views/Issue/index.html.twig
> +    importTitle: 'Import',
Please, translate this label.

2016-10-31 16:14 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Tests/Functional/Entity/Repository/IssueRepositoryTest.php
> +        $this->assertArrayHasKey('status', $result);
Please, provide better assertion of method results.

2016-11-04 16:13 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Tests/Functional/Entity/Repository/IssueRepositoryTest.php
> +        $this->assertEquals($result['status'], 'open');
Please, don't forget that first argument should contain expected value, and second argument - actual value.

2016-11-04 16:15 UTC, yshyshkin commented on src/Academic/Bundle/BugTrackingBundle/Placeholder/PlaceholderFilter.php
> +     * PlaceholderFilter constructor.
Please, avoid useless (e.g. autogenerated) comments. Comments should provide valuable information for developer, if they don't do that - it's better to remove them. In this case would be better to have only phpdoc in method comment.

2019-04-17 07:53 UTC, closed without merging